import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  featuredImage: Media
  author: User
}

export const post4En: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  featuredImage,
  author,
}) => {
  return {
    title:
      'VUP Earns Prestigious EcoVadis Silver: How Our Research-Driven Chemical Specialties Pave the Way for a Sustainable Future',
    type: 'news',
    featured: true,
    description:
      'VUP proudly announces achieving EcoVadis Silver Medal, placing us in the top 9% of companies worldwide for sustainability performance in chemical research and production.',
    featuredImage: featuredImage.id,
    author: author,
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'We are immensely proud to announce a landmark achievement for VUP, a.s.: the award of a Silver Medal by EcoVadis, the globally trusted standard for business sustainability ratings. This significant recognition places VUP in the top 9% of companies worldwide within our specialized sector of chemical research and production.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Achievement Highlight',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'EcoVadis Silver Medal:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Top 9% of companies worldwide in chemical research and production sector for sustainability performance.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "It's a powerful affirmation of our more than 70-year legacy dedicated to innovation, quality, and, increasingly, a formalized commitment to sustainable practices. For our valued partners, this VUP EcoVadis Silver rating is more than an accolade. It is a clear signal of our robust ESG framework and our deep-seated dedication to responsible manufacturing.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Understanding EcoVadis: The Global Benchmark for Sustainability',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "EcoVadis provides one of the world's most comprehensive and trusted assessments of company sustainability performance. Their methodology evaluates companies across four key themes: Environmental impact, Labor & Human Rights, Ethics, and Sustainable Procurement. Achieving a medal, particularly Silver, indicates a company has a structured and proactive approach to sustainability.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "VUP's Journey to Silver: A Legacy of Innovation and Responsibility",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "VUP's attainment of the EcoVadis Silver medal is not a recent pivot but the culmination of decades of dedicated work. Our foundation as a research institute, the Výskumný Ústav Petrochémie (Research Institute of Petrochemistry), has instilled a culture of continuous improvement and problem-solving.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our core mission involves not just manufacturing chemicals, but pioneering R&D chemical specialties. Our work in methylolalkanoic acids like DMPA (Dimethylolpropionic Acid) and DMBA (Dimethylolbutyric Acid) has been pivotal in enabling the shift towards waterborne polyurethane dispersions (PUDs) and other coatings, significantly reducing VOC emissions compared to traditional solvent-based systems.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our Specialized Products and Sustainability Impact',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The production of hindered amines such as TEMP (2,2,6,6-Tetramethylpiperidine) and its renowned derivative TEMPO (2,2,6,6-Tetramethylpiperidin-1-oxyl) serves specialized markets including polymer additives and pharmaceutical intermediates. TEMPO is a crucial catalyst for selective and green oxidation processes in organic synthesis.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "VUP's expertise extends to custom synthesis and unique products like DAPEG (Poly(ethylene glycol)bis(3-aminopropyl) terminated), which finds applications in the demanding biomedical field. Developing materials for such sensitive uses requires an exceptionally high level of quality control, safety, and ethical consideration.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'What This Means for Our Partners',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'This EcoVadis Silver rating offers our partners tangible benefits: assurance of a robust ESG framework, enhanced supply chain resilience, access to innovative and responsibly produced chemicals, support for your sustainability goals, and strengthened trust and reputation through alignment with a recognized sustainable partner.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Building a More Sustainable Future Together',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: "VUP, a.s's EcoVadis Silver Medal is a testament to our 70-year journey of innovation, quality, and an evolving, deepening commitment to sustainability. It offers our partners globally the assurance that VUP is a reliable, forward-thinking supplier dedicated to not just chemical excellence, but also to building sustainable partnerships.",
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    tags: [
      { tag: 'Sustainability' },
      { tag: 'EcoVadis' },
      { tag: 'ESG' },
      { tag: 'Chemical Specialties' },
      { tag: 'Environmental Responsibility' },
    ],
    relatedProducts: [],
    relatedServices: [],
    industries: [],
    meta: {
      title: 'VUP Earns EcoVadis Silver Medal for Sustainability Excellence',
      description:
        'VUP proudly announces achieving EcoVadis Silver Medal, placing us in the top 9% of companies worldwide for sustainability performance in chemical research and production.',
      image: featuredImage.id,
    },
    publishedAt: '2024-01-20T10:00:00.000Z',
    slug: 'vup-ecovadis-silver-sustainability-award',
    _status: 'published',
  }
}

export const post4Sk: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  featuredImage,
  author,
}) => {
  return {
    title:
      'VUP získava prestížnu medailu EcoVadis Silver: Ako naše chemické špeciality riadené výskumom utvárajú udržateľnú budúcnosť',
    type: 'news',
    featured: true,
    description:
      'VUP s hrdosťou oznamuje získanie medaily EcoVadis Silver, ktorá nás radí medzi 9 % najlepších spoločností na svete v oblasti udržateľného výkonu v chemickom výskume a výrobe.',
    featuredImage: featuredImage.id,
    author: author,
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'S obrovskou hrdosťou oznamujeme míľnikový úspech pre VUP, a.s.: udelenie striebornej medaily EcoVadis, globálne dôveryhodného štandardu pre hodnotenie firemnej udržateľnosti. Toto významné ocenenie radí VUP medzi 9 % najlepších spoločností na svete v našom špecializovanom sektore chemického výskumu a výroby.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Zdôraznenie úspechu',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'Strieborná medaila EcoVadis:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Medzi 9 % najlepších spoločností na svete v sektore chemického výskumu a výroby z hľadiska udržateľného výkonu.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Je to silné potvrdenie našej viac ako 70-ročnej tradície venovanej inovácií, kvalite a čoraz viac formalizovanému záväzku k udržateľným praktikám. Pre našich cenných partnerov je toto hodnotenie VUP EcoVadis Silver viac ako ocenenie. Je to jasný signál nášho robustného ESG rámca a našej hlboko zakotvenej oddanosti zodpovednej výrobe.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Pochopenie EcoVadis: Globálny benchmark pre udržateľnosť',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'EcoVadis poskytuje jedno z najkomplexnejších a najdôveryhodnejších hodnotení výkonu firemnej udržateľnosti na svete. Ich metodológia hodnotí spoločnosti v štyroch kľúčových témach: Environmentálny vplyv, Pracovné a ľudské práva, Etika a Udržateľné obstarávanie. Získanie medaily, najmä striebornej, naznačuje, že spoločnosť má štruktúrovaný a proaktívny prístup k udržateľnosti.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Cesta VUP k striebru: Dedičstvo inovácií a zodpovednosti',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Dosiahnutie striebornej medaily EcoVadis spoločnosťou VUP nie je nedávnym obratom, ale vyvrcholením desaťročí oddanej práce. Naše základy ako výskumného ústavu, Výskumný Ústav Petrochémie, nám vštepili kultúru neustáleho zlepšovania a riešenia problémov.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Naše hlavné poslanie zahŕňa nielen výrobu chemikálií, ale aj priekopnícke chemické špeciality výskumu a vývoja. Naša práca v oblasti metyloalkánových kyselín, ako je DMPA (kyselina dimetylolopropionová) a DMBA (kyselina dimetylomaslová), bola kľúčová pri umožnení prechodu na polyuretánové disperzie na vodnej báze (PUD) a iné povlaky, čím sa výrazne znižujú emisie VOC v porovnaní s tradičnými systémami na báze rozpúšťadiel.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Naše špecializované produkty a dopad na udržateľnosť',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Výroba bránených amínov, ako sú TEMP (2,2,6,6-tetrametylpiperidín) a jeho známy derivát TEMPO (2,2,6,6-tetrametylpiperidín-1-oxyl), slúži špecializovaným trhom vrátane polymerných aditív a farmaceutických medziproduktov. TEMPO je kľúčový katalyzátor pre selektívne a zelené oxidačné procesy v organickej syntéze.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Odbornosť VUP sa rozširuje na zákazkovú syntézu a jedinečné produkty, ako je DAPEG (Poly(etylénglykol)bis(3-aminopropyl) terminovaný), ktorý nachádza aplikácie v náročnej biomedicínskej oblasti. Vývoj materiálov pre také citlivé použitia vyžaduje výnimočne vysokú úroveň kontroly kvality, bezpečnosti a etického uváženia.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Čo to znamená pre našich partnerov',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Toto hodnotenie EcoVadis Silver ponúka našim partnerom hmatateľné výhody: záruku robustného ESG rámca, zvýšenú odolnosť dodávateľského reťazca, prístup k inovatívnym a zodpovedne vyrobeným chemikáliám, podporu vašich cieľov udržateľnosti a posilnenú dôveru a povesť prostredníctvom zladenia s uznaným udržateľným partnerom.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Budovanie udržateľnejšej budúcnosti spoločne',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Strieborná medaila EcoVadis spoločnosti VUP, a.s. je svedectvom našej 70-ročnej cesty inovácií, kvality a rozvíjajúceho sa, prehlbujúceho sa záväzku k udržateľnosti. Ponúka našim partnerom po celom svete istotu, že VUP je spoľahlivý, perspektívny dodávateľ oddaný nielen chemickej excelencii, ale aj budovaniu udržateľných partnerstiev.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    tags: [
      { tag: 'Udržateľnosť' },
      { tag: 'EcoVadis' },
      { tag: 'ESG' },
      { tag: 'Chemické špeciality' },
      { tag: 'Environmentálna zodpovednosť' },
    ],
    relatedProducts: [],
    relatedServices: [],
    industries: [],
    meta: {
      title: 'VUP získava medailu EcoVadis Silver za excelentnosť v udržateľnosti',
      description:
        'VUP s hrdosťou oznamuje získanie medaily EcoVadis Silver, ktorá nás radí medzi 9 % najlepších spoločností na svete v oblasti udržateľného výkonu v chemickom výskume a výrobe.',
      image: featuredImage.id,
    },
    publishedAt: '2024-01-20T10:00:00.000Z',
    slug: 'vup-ecovadis-silver-sustainability-award',
    _status: 'published',
  }
}

export const post4Jp: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  featuredImage,
  author,
}) => {
  return {
    title:
      'VUP、権威あるEcoVadis Silverを獲得：当社の研究主導型特殊化学品が持続可能な未来を切り開く',
    type: 'news',
    featured: true,
    description:
      'VUPは、化学研究および生産における持続可能性パフォーマンスで世界のトップ9％に位置するEcoVadis Silver Medalの獲得を誇らしく発表します。',
    featuredImage: featuredImage.id,
    author: author,
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '私たちはVUP, a.s.にとって画期的な成果を発表できることを非常に誇りに思います：世界的に信頼されているビジネス持続可能性評価の基準であるEcoVadisによるSilver Medalの授与です。この重要な認識により、VUPは化学研究および生産という当社の専門分野において世界のトップ9％に位置付けられます。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '成果のハイライト',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'EcoVadis Silver Medal:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' 化学研究および生産セクターにおける持続可能性パフォーマンスで世界のトップ9％。',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'これは、イノベーション、品質、そしてますます形式化された持続可能な実践へのコミットメントに捧げられた70年以上の遺産の強力な確認です。私たちの貴重なパートナーにとって、このVUP EcoVadis Silver評価は単なる賞賛以上のものです。これは、当社の堅牢なESGフレームワークと責任ある製造への深い献身の明確なシグナルです。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'EcoVadisの理解：持続可能性のグローバルベンチマーク',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'EcoVadisは、世界で最も包括的で信頼性の高い企業の持続可能性パフォーマンスの評価の1つを提供しています。彼らの方法論は、環境への影響、労働と人権、倫理、持続可能な調達という4つの主要テーマにわたって企業を評価します。メダル、特にSilverを獲得することは、企業が持続可能性に対して構造化された積極的なアプローチを持っていることを示しています。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'VUPのSilverへの道のり：イノベーションと責任の遺産',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'VUPのEcoVadis Silverメダルの獲得は最近の転換ではなく、数十年にわたる献身的な仕事の集大成です。研究機関としての私たちの基盤である石油化学研究所（Výskumný Ústav Petrochémie）は、継続的改善と問題解決の文化を植え付けました。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '私たちの核心的使命は、単に化学品を製造するだけでなく、研究開発化学特殊品の開拓を含みます。DMPA（ジメチロールプロピオン酸）やDMBA（ジメチロール酪酸）などのメチロールアルカン酸における私たちの仕事は、水性ポリウレタン分散液（PUD）やその他のコーティングへの移行を可能にする上で極めて重要であり、従来の溶剤系システムと比較してVOC排出を大幅に削減しています。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '当社の特殊製品と持続可能性への影響',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'TEMP（2,2,6,6-テトラメチルピペリジン）やその有名な誘導体TEMPO（2,2,6,6-テトラメチルピペリジン-1-オキシル）などのヒンダードアミンの生産は、ポリマー添加剤や医薬中間体を含む特殊市場に対応しています。TEMPOは、有機合成における選択的でグリーンな酸化プロセスのための重要な触媒です。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'VUPの専門知識は、DAPEG（ポリ（エチレングリコール）ビス（3-アミノプロピル）末端）などのカスタム合成およびユニークな製品にまで及び、これは要求の厳しいバイオメディカル分野での用途を見出しています。このような繊細な用途のための材料を開発するには、非常に高いレベルの品質管理、安全性、倫理的配慮が必要です。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'これがパートナーにとって意味すること',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'このEcoVadis Silver評価は、パートナーに具体的な利益を提供します：堅牢なESGフレームワークの保証、サプライチェーンの回復力の強化、革新的で責任を持って生産された化学品へのアクセス、持続可能性目標のサポート、認められた持続可能なパートナーとの提携による信頼と評判の強化。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'より持続可能な未来を共に構築する',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'VUP, a.s.のEcoVadis Silver Medalは、イノベーション、品質、そして進化し深化する持続可能性へのコミットメントという70年の旅の証です。これは、世界中のパートナーに、VUPが化学的卓越性だけでなく、持続可能なパートナーシップの構築にも専念する信頼性の高い先進的なサプライヤーであるという保証を提供します。',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    tags: [
      { tag: '持続可能性' },
      { tag: 'EcoVadis' },
      { tag: 'ESG' },
      { tag: '化学特殊品' },
      { tag: '環境責任' },
    ],
    relatedProducts: [],
    relatedServices: [],
    industries: [],
    meta: {
      title: 'VUP、持続可能性の卓越性によりEcoVadis Silver Medalを獲得',
      description:
        'VUPは、化学研究および生産における持続可能性パフォーマンスで世界のトップ9％に位置するEcoVadis Silver Medalの獲得を誇らしく発表します。',
      image: featuredImage.id,
    },
    publishedAt: '2024-01-20T10:00:00.000Z',
    slug: 'vup-ecovadis-silver-sustainability-award',
    _status: 'published',
  }
}
